- name: Deploy Application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        src: k8s/deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        src: k8s/service.yaml
