apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-dotnet-app
  template:
    metadata:
      labels:
        app: my-dotnet-app
    spec:
      containers:
        - name: my-dotnet-app
          image: my-dotnet8-app:latest  # No registry needed
          imagePullPolicy: IfNotPresent  # Prevent pulling from remote registry
          ports:
            - containerPort: 8080
