apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-app-service
spec:
  selector:
    app: my-dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Works for local Kubernetes (Kind)
